### ISSUE TITLE
点击网络物品后台报错

### ISSUE THREAD

**Issue by cat-catmiao** [SlimefunGuguProject/Networks#122]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

`[10:33:40 ERROR]: [Slimefun] An exception thrown while handling the click: 
java.lang.ClassCastException: Cannot cast io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack to org.bukkit.craftbukkit.inventory.CraftItemStack
        at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at Slimefun-d36ce9d-Beta.jar/me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.replaceExistingItem(ChestMenu.java:277) ~[Slimefun-d36ce9d-Beta.jar:?]
        at Networks-Build 96 (git 284c2a5).jar/io.github.sefiraat.networks.slimefun.groups.MainFlexGroup.setupPage(MainFlexGroup.java:89) ~[Networks-Build 96 (git 284c2a5).jar:?]
        at Networks-Build 96 (git 284c2a5).jar/io.github.sefiraat.networks.slimefun.groups.MainFlexGroup.open(MainFlexGroup.java:74) ~[Networks-Build 96 (git 284c2a5).jar:?]
        at Slimefun-d36ce9d-Beta.jar/io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.openItemGroup(SurvivalSlimefunGuide.java:236) ~[Slimefun-d36ce9d-Beta.jar:?]
        at Slimefun-d36ce9d-Beta.jar/io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.lambda$showItemGroup$4(SurvivalSlimefunGuide.java:196) ~[Slimefun-d36ce9d-Beta.jar:?]
        at Slimefun-d36ce9d-Beta.jar/me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:59) ~[Slimefun-d36ce9d-Beta.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor307.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3204) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

当点击菜单的网络物品的时候，后台出现了这个错误，使用的服务器版本是1.21

### 复现步骤

1.在1.21版本运行该插件，然后点击粘液菜单的网络物品，后台会出现该报错，服务器系统未linux系统。

### 预期行为

错误分析
错误原因：

java
java.lang.ClassCastException: Cannot cast io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack to org.bukkit.craftbukkit.inventory.CraftItemStack
这是因为在某个地方，代码试图将 SlimefunItemStack 转换为 CraftItemStack，这在 Java 中是不允许的，因为它们并没有继承关系。

具体出错位置：

java
at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46)
at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97)
at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100)
at Slimefun-d36ce9d-Beta.jar/me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.replaceExistingItem(ChestMenu.java:277)
错误发生在调用 CraftItemStack.getCraftStack 方法时，该方法试图将一个 SlimefunItemStack 对象转换为 CraftItemStack 对象。

上下文：

java
at Networks-Build 96 (git 284c2a5).jar/io.github.sefiraat.networks.slimefun.groups.MainFlexGroup.setupPage(MainFlexGroup.java:89)
at Networks-Build 96 (git 284c2a5).jar/io.github.sefiraat.networks.slimefun.groups.MainFlexGroup.open(MainFlexGroup.java:74)
错误发生在 MainFlexGroup 类的 setupPage 方法中，该方法可能涉及到设置某种菜单或界面时的物品堆栈。

可能的解决方案
检查类型转换：
确保在调用 CraftItemStack 的方法时，传递的对象确实是 CraftItemStack 类型的。如果需要将 SlimefunItemStack 转换为 CraftItemStack，需要找到正确的转换方式。

使用正确的转换方法：
如果需要从 SlimefunItemStack 获取 CraftItemStack 对象，通常情况下可能需要通过一些辅助方法或 API 提供的转换函数。例如，检查 Slimefun API 是否提供了将 SlimefunItemStack 转换为 CraftItemStack 的方法。

代码修改建议：

java
// 假设有一个方法可以从 SlimefunItemStack 获取 CraftItemStack
CraftItemStack craftItemStack = convertToCraftItemStack(slimefunItemStack);
inventory.setItem(slot, craftItemStack);
检查插件兼容性：
确保所使用的 Slimefun 和 Purpur 版本是兼容的。不同版本的 API 可能有所不同，导致类型转换错误。

调试日志：
在转换前添加调试日志，确保传递的对象类型是预期的。

java
if (slimefunItemStack instanceof CraftItemStack) {
    // Safe to cast and use
    CraftItemStack craftItemStack = (CraftItemStack) slimefunItemStack;
} else {
    // Log an error or handle the case where it's not a CraftItemStack
    System.out.println("Expected CraftItemStack but got " + slimefunItemStack.getClass().getName());
}
通过这些方法，可以进一步定位并解决这个类型转换问题。这是Ai分析的结果。

### 服务端软件

Purpur

### Minecraft 版本

1.21

### Slimefun版本

`[10:41:11 INFO]: Slimefun 运行的服务器环境:
[10:41:11 INFO]: Purpur 1.21-2275-82ccc76 (MC: 1.21)
[10:41:11 INFO]: Slimefun d36ce9d-Beta
[10:41:11 INFO]: Java 21
[10:41:11 INFO]: 
[10:41:11 INFO]: 由 StarWishsama 汉化
[10:41:11 INFO]: 请不要将此版本信息截图到 Discord/Github 反馈 Bug
[10:41:11 INFO]: 优先到汉化页面反馈
[10:41:11 INFO]: 
[10:41:11 INFO]: 安装的附属插件: (7)
[10:41:11 INFO]:   Networks vBuild 96 (git 284c2a5)
[10:41:11 INFO]:   InfinityExpansion vBuild 15 (git bebf0bd)
[10:41:11 INFO]:   Supreme vBuild 19 (git df50bc1)
[10:41:11 INFO]:   GuizhanLibPlugin vBuild 45 (git 7aef1af)
[10:41:11 INFO]:   SlimeGlue v1.0.2-7f3bca4
[10:41:11 INFO]:   FluffyMachines vBuild 35 (git 8a81689)
[10:41:11 INFO]:   ExoticGarden vBuild 18 (git a42cad0)
`

### 插件版本

Networks-Build 96 (git 284c2a5)

**Comment by ybw0014** [comment]
不用塞 AI 结果，使用本体的 Insider 版本，已修复
