### ISSUE TITLE
I can not run Networks plugin

### ISSUE THREAD

**Issue by Lubenwei-RGB** [SlimefunGuguProject/Networks#125]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

[15:49:22 ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem
java.lang.IllegalStateException: This game version UNKNOWN not supports Virtual DisplayItem.
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:425) ~[QuickShop7adf30b949484fda9595d1508976e83b.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[QuickShop7adf30b949484fda9595d1508976e83b.jar:?]
        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[QuickShop7adf30b949484fda9595d1508976e83b.jar:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[QuickShop7adf30b949484fda9595d1508976e83b.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:644) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:555) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1130) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:54:09 ERROR]: [Slimefun] An exception thrown while handling the click:
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at io.github.sefiraat.networks.slimefun.groups.MainFlexGroup.open(MainFlexGroup.java:63) ~[Networks-Build 96 (git 284c2a5).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.openItemGroup(SurvivalSlimefunGuide.java:235) ~[Slimefun-2024.04-release.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.lambda$showItemGroup$4(SurvivalSlimefunGuide.java:195) ~[Slimefun-2024.04-release.jar:?]
        at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:59) ~[Slimefun-2024.04-release.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor121.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1460) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1437) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:112) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1550) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### 复现步骤

run my server

### 预期行为

代码写错了？

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.20.4

### Slimefun版本

Slimefun-2024.04-release

### 插件版本

96

**Comment by ybw0014** [comment]
附属不确保支持本体最新版release，请使用Beta版本
