### ISSUE TITLE
网格无法展示物品，推送器无法推送，挖掘网络机器无法掉落

### ISSUE THREAD

**Issue by JiangQiYan713** [SlimefunGuguProject/Networks#88]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

可能是容器格式引起的错误

### 复现步骤

```
[21:54:49] [Server thread/ERROR]: [Networks] Item "NTW_PUSHER" from Networks vBuild 76 zh-CN(ybw0014) (git bc8511f) has caused an Error!
[21:54:49] [Server thread/ERROR]: [Networks] You can report it here: https://github.com/ybw0014/Networks/issues/
[21:54:49] [Server thread/ERROR]: [Networks] An Error occurred while trying to create a BlockMenu
java.lang.IllegalStateException: Unable to access unloaded data!
	at com.xzavier0722.mc.plugin.slimefun4.storage.controller.ASlimefunDataContainer.checkData(ASlimefunDataContainer.java:55) ~[Slimefun-v2023.06-release.jar:?]
	at com.xzavier0722.mc.plugin.slimefun4.storage.controller.ASlimefunDataContainer.getData(ASlimefunDataContainer.java:73) ~[Slimefun-v2023.06-release.jar:?]
	at com.xzavier0722.mc.plugin.slimefun4.storage.util.StorageCacheUtils.getData(StorageCacheUtils.java:52) ~[Slimefun-v2023.06-release.jar:?]
	at io.github.sefiraat.networks.slimefun.network.NetworkDirectional$3.newInstance(NetworkDirectional.java:188) ~[Networks-Build 76 zh-CN(ybw0014) (git bc8511f).jar:?]
	at me.mrCookieSlime.Slimefun.api.inventory.BlockMenuPreset.lambda$newInstance$0(BlockMenuPreset.java:239) ~[Slimefun-v2023.06-release.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-547]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-547]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

挖掘方块后
```

[21:58:18] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Slimefun v2023.06-release
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
	at com.xzavier0722.mc.plugin.slimefun4.storage.controller.SlimefunChunkData.removeBlockData(SlimefunChunkData.java:70) ~[Slimefun-v2023.06-release.jar:?]
	at com.xzavier0722.mc.plugin.slimefun4.storage.controller.BlockDataController.removeBlock(BlockDataController.java:128) ~[Slimefun-v2023.06-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:192) ~[Slimefun-v2023.06-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:134) ~[Slimefun-v2023.06-release.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-547]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-547]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-547]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:377) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:336) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:300) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1871) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-547]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:58:47] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Slimefun v2023.06-release
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
	at com.xzavier0722.mc.plugin.slimefun4.storage.controller.SlimefunChunkData.removeBlockData(SlimefunChunkData.java:70) ~[Slimefun-v2023.06-release.jar:?]
	at com.xzavier0722.mc.plugin.slimefun4.storage.controller.BlockDataController.removeBlock(BlockDataController.java:128) ~[Slimefun-v2023.06-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:192) ~[Slimefun-v2023.06-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:134) ~[Slimefun-v2023.06-release.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-547]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-547]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-547]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:377) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:336) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:300) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1871) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-547]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:59:12] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Slimefun v2023.06-release
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
	at com.xzavier0722.mc.plugin.slimefun4.storage.controller.SlimefunChunkData.removeBlockData(SlimefunChunkData.java:70) ~[Slimefun-v2023.06-release.jar:?]
	at com.xzavier0722.mc.plugin.slimefun4.storage.controller.BlockDataController.removeBlock(BlockDataController.java:128) ~[Slimefun-v2023.06-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:192) ~[Slimefun-v2023.06-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:134) ~[Slimefun-v2023.06-release.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-547]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-547]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-547]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:377) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:336) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:300) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1871) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-547]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:59:49] [Server thread/INFO]: JiangQiYan issued server command: /sf versions
```

### 预期行为

正常使用

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

稍等

### 插件版本

76

**Comment by ybw0014** [comment]
先退回上个版本吧

**Comment by Xzavier0722** [comment]
本件第一个报错属于粘液本体逻辑问题，已在内测版修复。请关注后续公测版更新。
第二个问题无法复现，请提供详细复现手顺和条件。
