### ISSUE TITLE
网络远程访问器无法使用

### ISSUE THREAD

**Issue by aesopcmc** [SlimefunGuguProject/Networks#92]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

网络远程访问器无法使用，已经提示绑定网格成功，并且保持在激活的区块内，右键或左键网络远程访问器依然无效，无法打开

后台并没有报错，但是安装了领地插件，在领地中使用右键，控制就报错一次：

Residence Version: Residence v5.1.2.0
Paper Version: 1.19.3
Slimefun4 ext: Networks-Build 79 zh-CN(ybw0014) (git 3a763e9).jar

ps： 一下可能是领地插件的问题，网络附属已经更新到80.。
info:
[14:33:55 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.1.2.0"
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:660) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:127) ~[Residence5.1.2.0.jar:?]
at com.bekvon.bukkit.residence.slimeFun.SlimeFunResidenceModule.hasPermission(SlimeFunResidenceModule.java:48) ~[Residence5.1.2.0.jar:?]
at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[Slimefun-v2023.06-release.jar:?]
at io.github.sefiraat.networks.slimefun.tools.NetworkRemote$1.onResult(NetworkRemote.java:114) ~[[粘液科技扩展-网络]Networks-Build 79 zh-CN(ybw0014) (git 3a763e9).jar:?]
at io.github.sefiraat.networks.slimefun.tools.NetworkRemote$1.onResult(NetworkRemote.java:106) ~[[粘液科技扩展-网络]Networks-Build 79 zh-CN(ybw0014) (git 3a763e9).jar:?]
at com.xzavier0722.mc.plugin.slimefun4.storage.controller.ADataController.lambda$invokeCallback$2(ADataController.java:124) ~[Slimefun-v2023.06-release.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 复现步骤

无法使用，没有报错。

### 预期行为

我和朋友都测试过了无法使用

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun-v2023.06-release.jar

![image](https://github.com/SlimefunGuguProject/Networks/assets/25699609/e700854d-2964-4938-a554-b70c39b7db88)

### 插件版本

80

**Comment by ybw0014** [comment]
领地是不是最新的？我记得领地说这个会修的

**Comment by aesopcmc** [comment]
> > 领地是不是最新的？我记得领地说这个会修的
> 
> 是最新的Residence v5.1.2.0 版本，而且我离开了领地范围，测试了，也不起作用，不知道是不是领地插件依然有影响 ![image](https://user-images.githubusercontent.com/25699609/252367122-a5b1e926-07ff-4f96-83ba-789b3a435bf9.png)

如果作者说有更新，那估计目前还未跟新，不确定是否跟领地插件有关

**Comment by ybw0014** [comment]
领地的问题

**Comment by aesopcmc** [comment]
那好，我继续等领地更新~

**Comment by aesopcmc** [comment]
刚刚有测试。把领地插件去除了，也不行，甚至把粘液科技的文件夹删除重建了。
插件列表
![image](https://github.com/SlimefunGuguProject/Networks/assets/25699609/c5c0e275-f9ea-4fa2-9d28-ecb71d146ab2)

**Comment by ybw0014** [comment]
[b321cd1](https://github.com/SlimefunGuguProject/Networks/commit/b321cd196fda55bd0a717ab41af237296ae49d2f)
