### ISSUE TITLE
粘液物品无法输送进网络

### ISSUE THREAD

**Issue by aesopcmc** [SlimefunGuguProject/Networks#93]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

大部分粘液物品无法输送进网络，而原版物品可以，
期间查看到核心抛出异常：
[09:31:04] [Server thread/ERROR]: Could not pass event PrepareSmithingEvent to Slimefun vf30bdf2-canary
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.crafting.SmithingTableListener.onPrepareSmith(SmithingTableListener.java:48) ~[[粘液科技-核心]Slimefun-f30bdf2-canary.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1164.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-375]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1691) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.world.inventory.SmithingMenu.createResult(SmithingMenu.java:82) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu.slotsChanged(ItemCombinerMenu.java:80) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu$1.setChanged(ItemCombinerMenu.java:25) ~[?:?]
	at net.minecraft.world.SimpleContainer.setItem(SimpleContainer.java:203) ~[?:?]
	at net.minecraft.world.inventory.Slot.set(Slot.java:59) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:868) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:768) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu.quickMoveStack(ItemCombinerMenu.java:125) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:539) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3167) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-375]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 复现步骤

网络连接的大部分机器都出现了产出不能运送到网络种的情况

### 预期行为

粘液物品应该正常运送到网络

### 服务端软件

Spigot

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun vf30bdf2-canary

### 插件版本

Networks-Build 81 (git b321cd1)-shaded

**Comment by aesopcmc** [comment]
找到问题了。。是安装了xMikux的&eSlimefun-Resourcepack&7材质包问题导致NTB数据不一致。去除即可。
