### ISSUE TITLE
无限出现报错

### ISSUE THREAD

**Issue by xiaofengv233** [SlimefunGuguProject/Networks#95]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

无限出现这段报错

[11:54:00] [Craft Scheduler Thread - 48 - Slimefun/ERROR]: [dough: protection] An Error occured while querying the Protection Module: "SlimeGlue v1.0.2-b262a4a"
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:158) ~[[R][领地]Residence5.1.3.0.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:100) ~[[R][领地]Residence5.1.3.0.jar:?]
	at com.xzavier0722.mc.plugin.slimeglue.module.ResidenceModule.canBypassCheck(ResidenceModule.java:110) ~[[S][粘液附属 保护]SlimeGlue-1.0.2.jar:?]
	at com.xzavier0722.mc.plugin.slimeglue.module.ResidenceModule$1.bypassCheck(ResidenceModule.java:35) ~[[S][粘液附属 保护]SlimeGlue-1.0.2.jar:?]
	at com.xzavier0722.mc.plugin.slimeglue.slimefun.GlueProtectionModule.hasPermission(GlueProtectionModule.java:42) ~[[S][粘液附属 保护]SlimeGlue-1.0.2.jar:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[slimefun-230811-e565225-Insider.jar:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:167) ~[slimefun-230811-e565225-Insider.jar:?]
	at io.github.sefiraat.networks.slimefun.network.NetworkControlV.tryPasteBlock(NetworkControlV.java:113) ~[[N][网络]Networks-Build 82 (git f2c9653).jar:?]
	at io.github.sefiraat.networks.slimefun.network.NetworkControlV.onTick(NetworkControlV.java:64) ~[[N][网络]Networks-Build 82 (git f2c9653).jar:?]
	at io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:103) ~[[N][网络]Networks-Build 82 (git f2c9653).jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:167) ~[slimefun-230811-e565225-Insider.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:154) ~[slimefun-230811-e565225-Insider.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:121) ~[slimefun-230811-e565225-Insider.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:98) ~[slimefun-230811-e565225-Insider.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 复现步骤

1.开服就会出现

### 预期行为

应该正常

### 服务端软件

Purpur

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

slimefun-230811-e565225-Insider.jar

### 插件版本

82

**Comment by ybw0014** [comment]
Res不是说修了么，怎么又有了

**Comment by xiaofengv233** [comment]
> Res不是说修了么，怎么又有了

😂

**Comment by StarWishsama** [comment]
更新领地到 5.1.3.0

**Comment by xiaofengv233** [comment]
> 更新领地到 5.1.3.0

你看我发的报错，就是 Residence5.1.3.0 
这个领地版本😂

**Comment by StarWishsama** [comment]
那就更一下 SlimeGlue

**Comment by ybw0014** [comment]
stale
